@startuml
start
:Mostrar Menú Principal
1. Jugar
2. Ver Puntuaciones
3. Salir;
if (Opción == 1) then (Si)
    :Ir al Módulo de Juego;
else (No) 
    if (Opción == 2) then (sí)
    :Mostrar Puntuaciones;
    else (no)
    :Salir del Juego;
    endif
endif
stop
@enduml