@startuml
start
:Iniciar tableros;
:finJuego = False
seguirJugando = True;
if (seguirJugando == True) then (Sí)
  if (finJuego == True) then (Sí)
    :Turno de Juego;
    :Validar fin del juego;
  else (No)
    :Mostrar Marcadores;
  endif;
else (No)
endif;
stop
@enduml